### ISSUE TITLE
No such file or directory: '/tmp/trump_lasttweet'

### ISSUE THREAD

**Issue by perrycannon** [WebBreacher/trumpdroidretweeter#5]
Good afternoon, I receive an error

No such file or directory: '/tmp/trump_lasttweet'

Thank you

**Comment by WebBreacher** [comment]
From the command line try typing: 

`touch /tmp/trump_lasttweet`

**Comment by WebBreacher** [comment]
Closing since this is not an issue with the existing code base but with a modified version the user created.
